# Generated by Django 2.2.17 on 2020-12-23 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_concept_id', models.IntegerField(null=True)),
                ('year_of_birth', models.IntegerField(null=True)),
                ('month_of_birth', models.IntegerField(null=True)),
                ('day_of_birth', models.CharField(max_length=100, null=True)),
                ('birth_datetime', models.CharField(max_length=100, null=True)),
                ('race_concept_id', models.IntegerField(null=True)),
                ('ethnicity_concept_id', models.IntegerField(null=True)),
                ('location_id', models.IntegerField(null=True)),
                ('provider_id', models.IntegerField(null=True)),
                ('care_site_id', models.IntegerField(null=True)),
                ('person_source_value', models.CharField(max_length=100, null=True)),
                ('gender_source_value', models.CharField(max_length=100, null=True)),
                ('gender_source_concept_id', models.IntegerField(null=True)),
                ('race_source_value', models.CharField(max_length=100, null=True)),
                ('race_source_concept_id', models.IntegerField(null=True)),
                ('ethnicity_source_value', models.CharField(max_length=100, null=True)),
                ('ethnicity_source_concept_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitOccurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_concept_id', models.IntegerField(null=True)),
                ('visit_start_date', models.CharField(max_length=100, null=True)),
                ('visit_start_datetime', models.CharField(max_length=100, null=True)),
                ('visit_end_date', models.CharField(max_length=100, null=True)),
                ('visit_end_datetime', models.CharField(max_length=100, null=True)),
                ('visit_type_concept_id', models.IntegerField(null=True)),
                ('provider_id', models.IntegerField(null=True)),
                ('care_site_id', models.IntegerField(null=True)),
                ('visit_source_value', models.CharField(max_length=100, null=True)),
                ('visit_source_concept_id', models.IntegerField(null=True)),
                ('admitting_source_concept_id', models.IntegerField(null=True)),
                ('admitting_source_value', models.CharField(max_length=100, null=True)),
                ('discharge_to_concept_id', models.IntegerField(null=True)),
                ('discharge_to_source_value', models.CharField(max_length=100, null=True)),
                ('preceding_visit_occurrence_id', models.IntegerField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_concept_id', models.IntegerField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='DrugExposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_concept_id', models.IntegerField(null=True)),
                ('drug_exposure_start_date', models.CharField(max_length=100, null=True)),
                ('drug_exposure_start_datetime', models.CharField(max_length=100, null=True)),
                ('drug_exposure_end_date', models.CharField(max_length=100, null=True)),
                ('drug_exposure_end_datetime', models.CharField(max_length=100, null=True)),
                ('verbatim_end_date', models.CharField(max_length=100, null=True)),
                ('drug_type_concept_id', models.IntegerField(null=True)),
                ('stop_reason', models.CharField(max_length=100, null=True)),
                ('refills', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('days_supply', models.IntegerField(null=True)),
                ('sig', models.CharField(max_length=100, null=True)),
                ('route_concept_id', models.IntegerField(null=True)),
                ('lot_number', models.IntegerField(null=True)),
                ('provider_id', models.IntegerField(null=True)),
                ('visit_occurrence_id', models.IntegerField(null=True)),
                ('visit_detail_id', models.IntegerField(null=True)),
                ('drug_source_value', models.CharField(max_length=100, null=True)),
                ('drug_source_concept_id', models.IntegerField(null=True)),
                ('route_source_value', models.CharField(max_length=100, null=True)),
                ('dose_unit_source_value', models.CharField(max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.CharField(max_length=100, null=True)),
                ('death_datetime', models.CharField(max_length=100, null=True)),
                ('death_type_concept_id', models.IntegerField(null=True)),
                ('cause_concept_id', models.IntegerField(null=True)),
                ('cause_source_value', models.CharField(max_length=100, null=True)),
                ('cause_source_concept_id', models.IntegerField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_concept_id', models.IntegerField(null=True)),
                ('condition_start_date', models.CharField(max_length=100, null=True)),
                ('condition_start_datetime', models.CharField(max_length=100, null=True)),
                ('condition_end_date', models.CharField(max_length=100, null=True)),
                ('condition_end_datetime', models.CharField(max_length=100, null=True)),
                ('condition_type_concept_id', models.IntegerField(null=True)),
                ('stop_reason', models.CharField(max_length=100, null=True)),
                ('provider_id', models.IntegerField(null=True)),
                ('visit_occurrence_id', models.IntegerField(null=True)),
                ('visit_detail_id', models.IntegerField(null=True)),
                ('condition_source_value', models.CharField(max_length=100, null=True)),
                ('condition_source_concept_id', models.IntegerField(null=True)),
                ('condition_status_source_value', models.CharField(max_length=100, null=True)),
                ('condition_status_concept_id', models.IntegerField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
        ),
    ]
